django_girls/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('django_girls_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_girls_app/urls.py
"""Определяет схемы URL для django_girls_app"""
from django.urls import path
from . import views
app_name = 'django_girls_app'


urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница со списком всех тем
    path('topics/', views.topics, name='topics'),
    # Страница с подробной (все записи) информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),
    # Страница для добавления новой записи
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Страница для редактирования записи
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Определяет схемы URL для пользователей"""
from django.urls import path, include
from . import views
app_name = 'users'

urlpatterns = [
    # Включить URL авторизации по умолчанию
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации
    path('register/', views.register, name='register'),
    path('logoutme/', views.logout_view, name='logout_view'),
]

django_girls_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# MODEL-Topic: Stars, Planets, Animals.
class Topic(models.Model):
    """Тема, которую изучает пользователь"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Возвращает строковое представление модели"""
        return self.text

# MODEL-Entry: Sun is our.., Mercury is the.., Lion is a..
class Entry(models.Model):
    """Запись по теме"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Возвращает строковое представление модели"""
        return f"{self.text[:10]}..."

users/models.py
from django.db import models

# Create your models here.

django_girls_app/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':'Entry:'}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

django_girls_app/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
def index(request):
    """Домашняя страница приложения django_girls_app"""
    return render(request, 'django_girls_app/index.html')

@login_required
def topics(request):
    """Вывод списка тем"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}

    return render(request, 'django_girls_app/topics.html', context)

@login_required
def topic(request, topic_id):
    """Выводит одну тему и все ее записи"""
    topic = Topic.objects.get(id=topic_id)
    
    # Проверка того, что тема принадлежит текущему пользователю
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries}

    return render(request, 'django_girls_app/topic.html', context)

@login_required
def new_topic(request):
    """Определяет новую тему"""
    if request.method != 'POST':
        # Данные не отправлены, создается пустая форма
        form = TopicForm()
    else:
        # Отправляем данные POST, 
        # обработать данные
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('django_girls_app:topics')

    # Вывести пустую или недействительную форму
    context = {'form':form}
    return render(request, 'django_girls_app/new_topic.html', context)


    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries}

    return render(request, 'django_girls_app/topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Добавляем новую запись по конкретной теме"""
    topic = Topic.objects.get(id=topic_id)

    # Проверка того, что тема принадлежит текущему пользователю
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Данные не отправлены, создается пустая форма
        form = EntryForm()
    else:
        # Отправляем данные POST, 
        # обработать данные
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('django_girls_app:topic', topic_id=topic_id)

    # Вывести пустую или недействительную форму
    context = {'topic':topic, 'form':form}
    return render(request, 'django_girls_app/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    # Проверка того, что тема принадлежит текущему пользователю
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Данные не отправлены
        # Исходный запрос, форма заполняется данными текущей записи
        form = EntryForm(instance=entry)
    else:
        # Отправляем данные POST, 
        # обработать данные
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('django_girls_app:topic', topic_id=topic.id)

    # Вывести пустую или недействительную форму
    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'django_girls_app/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Редактирует нового пользователя"""
    if request.method != 'POST':
        # Выводит пустую форму регистрации
        form = UserCreationForm()
    else:
        # Обработка заполненной формы
        # Отправляем данные POST 
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу
            login(request, new_user)
            return redirect('django_girls_app:index')

    # Вывести пустую или недействительную форму
    context = {'form':form}
    return render(request, 'users/register.html', context)

def logout_view(request):
    logout(request)
    # Optionally, redirect to a success page
    return render(request, "registration/logged_out.html", {"Done":"Done!"})

django_girls_app/templates/django_girls_app/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Topics</title>
</head>
<body>
<p>
    <a href="{% url 'django_girls_app:index' %}">
        Django girls
    </a> - 
    <a href="{% url 'django_girls_app:topics' %}">
        Topics
    </a> - 
    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout_view' %}"> Log out </a>
    {% else %}
        <a href="{% url 'users:register' %}"> Register </a> - 
        <a href="{% url 'users:login' %}"> Log in </a>
    {% endif %}
</p>

{% block content %}{% endblock content %}
</body>
</html>

django_girls_app/templates/django_girls_app/edit_entry.html
{% extends "django_girls_app/base.html" %}
{% block content %}
  <p><a href="{% url 'django_girls_app:topic' topic.id %}">{{ topic }}</a></p>
  <p>Edit entry: </p>
  <form action="{% url 'django_girls_app:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>
  {% endblock content %}

django_girls_app/templates/django_girls_app/index.html
{% extends "django_girls_app/base.html" %}
{% block content %}
  <p>Create your topics</p>
  <p>Add some entries for every topic</p>
{% endblock content %}

django_girls_app/templates/django_girls_app/new_entry.html
{% extends "django_girls_app/base.html" %}
{% block content %}
  <p><a href="{% url 'django_girls_app:topic' topic.id %}">{{ topic }}</a></p>
  <p>Add a new entry:</p>
  <form action="{% url 'django_girls_app:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add entry</button>
  </form>
  {% endblock content %}

django_girls_app/templates/django_girls_app/new_topic.html
{% extends "django_girls_app/base.html" %}
{% block content %}
  <p>Add a new topic</p>
  <form action="{% url 'django_girls_app:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add topic</button>
  </form>
  {% endblock content %}

django_girls_app/templates/django_girls_app/topic.html
{% extends "django_girls_app/base.html" %}
{% block content %}
  <p>Topic: {{topic}}</p>

  <p>Entries</p>
  <p>
    <a href="{% url 'django_girls_app:new_entry' topic.id%}">add new entry</a>
  </p>

  <ul>
    {% for entry in entries %}
      <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
        <p><a href="{% url 'django_girls_app:edit_entry' entry.id%}">Edit entry</a></p>
      </li>
    {% empty %}
      <li>There are no entries for this topic yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}

django_girls_app/templates/django_girls_app/topics.html
{% extends "django_girls_app/base.html" %}
{% block content %}
  <p>Topics</p>
  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'django_girls_app:topic' topic.id %}">{{ topic }}</a>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>
  <a href="{% url 'django_girls_app:new_topic' %}"> Add a new topic: </a>
{% endblock content %}

users/templates/users/register.html
{% extends "django_girls_app/base.html" %}
{% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit"> register </button>
        <input type="hidden" name="next" value="{% url 'django_girls_app:index' %}" />
    </form>
{% endblock content %}